### ISSUE TITLE
Can't hit blocks on (most/some) Noodle Maps

### ISSUE THREAD

**Issue by RobSkop** [Aeroluna/Chroma#27]
I installed the newest Version of Chroma, Noodle and Heck and I tried some maps out to test all functionalities. 

One worked fine, however on all other maps I tested I wasn't able to hit the blocks correctly. I think the offset breaks because now and then I got a hit but almost all were misses. 

I disabled Chroma and tried the same maps again and then everything worked as intended.

(Tested maps: 14171 [only worked without chroma] ; 17e36 [Working with chroma] ; 11cf8 [only worked without chroma])

Here's a video of the issue: https://youtu.be/A-8wKtP8wOo

**Comment by Fatalution** [comment]
Seconding this, but the issue is not with Noodle maps. It's with _any_ Chroma map. It also affects replays' acc shown (as the map is being replayed in the game).

Steps to reproduce:

1. Launch the game with only core mods, Chroma, CustomJSONData, and Heck installed
2. Enable Chroma events if disabled
3. Launch any Chroma map
4. Enjoy not being able to hit a block
5. Disable Chroma events
6. Enjoy hitting bloqs with broken lights

Some interesting stuff:
Somehow I have managed to get bloqs hittable, but also got this weird bug: https://imgur.com/oIy8waZ
Restarting the map fixed the saber colors, but the bloqs weren't hittable again.

That got me thinking the new SaberColorizer has something to do with this. Lo' and behold, the _latest.log uncovers that issue
[_latest.log](https://github.com/Aeroluna/Chroma/files/6593629/_latest.log)

**Comment by Gh0stscript** [comment]
Also experiencing this.

"Allow custom song colors" enabled does not seem to be working workaround in my case.

**Comment by DUBBLE3535** [comment]
It doesn't work for me either

**Comment by Aeroluna** [comment]
Fixed in Chroma v2.4.6 https://github.com/Aeroluna/Chroma/commit/fcb73ce32a6a665f2aa3975b76c723ab738a3e92.

**Comment by ChrisJAllan** [comment]
Still an issue in v2.4.6. Attaching what I think is the relevant parts of the log (I was playing for a couple hours, and it didn't happen at first).

[chroma_error.log](https://github.com/Aeroluna/Chroma/files/6596545/chroma_error.log)

**Comment by homebrewuser** [comment]
i NeEd ThIs FiXeD

**Comment by Fatalution** [comment]
> i NeEd ThIs FiXeD

This is fixed. Please update your Chroma
